using Microsoft.VisualBasic;
using SSW;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------


namespace SSW.Website.WebUI.Masters
{

	public partial class SubPage
	{

		///<summary>
		///title control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder title;
		///<summary>
		///titleSales control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder titleSales;
		///<summary>
		///titleCase control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder titleCase;
		///<summary>
		///titleUX control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder titleUX;
		///<summary>
		///featureimage control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder featureimage;
		///<summary>
		///index control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder index;
		///<summary>
		///showcase control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder showcase;
		///<summary>
		///maincontentCase control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder maincontentCase;
		///<summary>
		///SiteMapPathMaster control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.SiteMapPath SiteMapPathMaster;
		///<summary>
		///maincontentFull control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder maincontentFull;
		///<summary>
		///maincontent control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder maincontent;
		///<summary>
		///fackbookFrame control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>


		protected global::System.Web.UI.WebControls.ContentPlaceHolder sidebar;
		///<summary>
		///newsletterEmailTextBox control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.TextBox newsletterEmailTextBox;
		///<summary>
		///newsletterSignUpButton control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		private global::System.Web.UI.WebControls.Button withEventsField_newsletterSignUpButton;
		protected global::System.Web.UI.WebControls.Button newsletterSignUpButton {
			get { return withEventsField_newsletterSignUpButton; }
			set {
				if (withEventsField_newsletterSignUpButton != null) {
					withEventsField_newsletterSignUpButton.Click -= newsletterSignUpButton_Click;
				}
				withEventsField_newsletterSignUpButton = value;
				if (withEventsField_newsletterSignUpButton != null) {
					withEventsField_newsletterSignUpButton.Click += newsletterSignUpButton_Click;
				}
			}

		}
		///<summary>
		///RegularExpressionValidator1 control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		///<summary>
		///HeadingPlaceHolder control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadingPlaceHolder;
		///<summary>
		///lblHeading control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.Label lblHeading;
	}
}
