//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSW.Website.WebUI {
    
    
    public partial class Raven {
        
        /// <summary>
        /// OpenTime3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SSW.Website.WebUI.Components.OpenTime OpenTime3;
        
        /// <summary>
        /// OpenTime4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SSW.Website.WebUI.Components.OpenTime OpenTime4;
        
        /// <summary>
        /// OpenTime5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SSW.Website.WebUI.Components.OpenTime OpenTime5;
        
        /// <summary>
        /// OpenTime1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SSW.Website.WebUI.Components.OpenTime OpenTime1;
    }
}
