using Microsoft.VisualBasic;
using SSW;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



 // ERROR: Not supported in C#: OptionDeclaration
public partial class Tester
{
	protected System.Web.UI.HtmlControls.HtmlHead Head1;
	protected System.Web.UI.HtmlControls.HtmlForm form1;
	protected System.Web.UI.WebControls.Label Label2;
	protected System.Web.UI.WebControls.TextBox txtPCID;
	protected System.Web.UI.WebControls.Label Label3;
	protected System.Web.UI.WebControls.TextBox txtClient;
	protected System.Web.UI.WebControls.Label Label4;
	protected System.Web.UI.WebControls.TextBox txtProduct;
	private System.Web.UI.WebControls.Button withEventsField_Button1;
	protected System.Web.UI.WebControls.Button Button1 {
		get { return withEventsField_Button1; }
		set {
			if (withEventsField_Button1 != null) {
				withEventsField_Button1.Click -= Button1_Click;
			}
			withEventsField_Button1 = value;
			if (withEventsField_Button1 != null) {
				withEventsField_Button1.Click += Button1_Click;
			}
		}
	}
}
