//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace SSWWebServicePaymentSystem {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaymentSystemSoap", Namespace="http://tempuri.org/")]
    public partial class PaymentSystem : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubmitPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCreditCardValidOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestSubmitPaymentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PaymentSystem() {
            this.Url = "http://webservices.internal.ssw.com.au/SSW.PaymentSystem.WebService/PaymentSystem" +
                ".asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitPaymentCompletedEventHandler SubmitPaymentCompleted;
        
        /// <remarks/>
        public event IsCreditCardValidCompletedEventHandler IsCreditCardValidCompleted;
        
        /// <remarks/>
        public event TestSubmitPaymentCompletedEventHandler TestSubmitPaymentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PaymentResult SubmitPayment(CreditCardDetails creditCardDetails, PaymentDetails paymentDetails, OrderInfo orderInfo) {
            object[] results = this.Invoke("SubmitPayment", new object[] {
                        creditCardDetails,
                        paymentDetails,
                        orderInfo});
            return ((PaymentResult)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitPaymentAsync(CreditCardDetails creditCardDetails, PaymentDetails paymentDetails, OrderInfo orderInfo) {
            this.SubmitPaymentAsync(creditCardDetails, paymentDetails, orderInfo, null);
        }
        
        /// <remarks/>
        public void SubmitPaymentAsync(CreditCardDetails creditCardDetails, PaymentDetails paymentDetails, OrderInfo orderInfo, object userState) {
            if ((this.SubmitPaymentOperationCompleted == null)) {
                this.SubmitPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitPaymentOperationCompleted);
            }
            this.InvokeAsync("SubmitPayment", new object[] {
                        creditCardDetails,
                        paymentDetails,
                        orderInfo}, this.SubmitPaymentOperationCompleted, userState);
        }
        
        private void OnSubmitPaymentOperationCompleted(object arg) {
            if ((this.SubmitPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitPaymentCompleted(this, new SubmitPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsCreditCardValid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CCValidationResult IsCreditCardValid(CreditCardDetails creditCardDetails, OrderInfo orderInfo, PaymentDetails paymentDetails) {
            object[] results = this.Invoke("IsCreditCardValid", new object[] {
                        creditCardDetails,
                        orderInfo,
                        paymentDetails});
            return ((CCValidationResult)(results[0]));
        }
        
        /// <remarks/>
        public void IsCreditCardValidAsync(CreditCardDetails creditCardDetails, OrderInfo orderInfo, PaymentDetails paymentDetails) {
            this.IsCreditCardValidAsync(creditCardDetails, orderInfo, paymentDetails, null);
        }
        
        /// <remarks/>
        public void IsCreditCardValidAsync(CreditCardDetails creditCardDetails, OrderInfo orderInfo, PaymentDetails paymentDetails, object userState) {
            if ((this.IsCreditCardValidOperationCompleted == null)) {
                this.IsCreditCardValidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCreditCardValidOperationCompleted);
            }
            this.InvokeAsync("IsCreditCardValid", new object[] {
                        creditCardDetails,
                        orderInfo,
                        paymentDetails}, this.IsCreditCardValidOperationCompleted, userState);
        }
        
        private void OnIsCreditCardValidOperationCompleted(object arg) {
            if ((this.IsCreditCardValidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCreditCardValidCompleted(this, new IsCreditCardValidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestSubmitPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TestSubmitPayment() {
            object[] results = this.Invoke("TestSubmitPayment", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void TestSubmitPaymentAsync() {
            this.TestSubmitPaymentAsync(null);
        }
        
        /// <remarks/>
        public void TestSubmitPaymentAsync(object userState) {
            if ((this.TestSubmitPaymentOperationCompleted == null)) {
                this.TestSubmitPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestSubmitPaymentOperationCompleted);
            }
            this.InvokeAsync("TestSubmitPayment", new object[0], this.TestSubmitPaymentOperationCompleted, userState);
        }
        
        private void OnTestSubmitPaymentOperationCompleted(object arg) {
            if ((this.TestSubmitPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestSubmitPaymentCompleted(this, new TestSubmitPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCardDetails {
        
        private string creditCardNumberField;
        
        private string creditCardNameField;
        
        private string expiryYearField;
        
        private string expiryMonthField;
        
        private string verificationNumberField;
        
        private CreditCardType creditCardTypeField;
        
        /// <remarks/>
        public string CreditCardNumber {
            get {
                return this.creditCardNumberField;
            }
            set {
                this.creditCardNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CreditCardName {
            get {
                return this.creditCardNameField;
            }
            set {
                this.creditCardNameField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryYear {
            get {
                return this.expiryYearField;
            }
            set {
                this.expiryYearField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryMonth {
            get {
                return this.expiryMonthField;
            }
            set {
                this.expiryMonthField = value;
            }
        }
        
        /// <remarks/>
        public string VerificationNumber {
            get {
                return this.verificationNumberField;
            }
            set {
                this.verificationNumberField = value;
            }
        }
        
        /// <remarks/>
        public CreditCardType CreditCardType {
            get {
                return this.creditCardTypeField;
            }
            set {
                this.creditCardTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CreditCardType {
        
        /// <remarks/>
        VISA,
        
        /// <remarks/>
        MasterCard,
        
        /// <remarks/>
        AmericanExpress,
        
        /// <remarks/>
        Diners,
        
        /// <remarks/>
        BankCard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CCValidationResult {
        
        private bool resultField;
        
        private string resultTextField;
        
        private string encryptedOrderNumberField;
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string ResultText {
            get {
                return this.resultTextField;
            }
            set {
                this.resultTextField = value;
            }
        }
        
        /// <remarks/>
        public string EncryptedOrderNumber {
            get {
                return this.encryptedOrderNumberField;
            }
            set {
                this.encryptedOrderNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentResult {
        
        private string responseTextField;
        
        private string responseCodeDescriptionField;
        
        private string transactionIdentifierField;
        
        private string transactionRecordNumberField;
        
        private string settlementDateField;
        
        private string orderNumberField;
        
        private string receiptNumberField;
        
        private string orderNumberSignatureField;
        
        private PaymentStatusEnum paymentStatusField;
        
        /// <remarks/>
        public string ResponseText {
            get {
                return this.responseTextField;
            }
            set {
                this.responseTextField = value;
            }
        }
        
        /// <remarks/>
        public string ResponseCodeDescription {
            get {
                return this.responseCodeDescriptionField;
            }
            set {
                this.responseCodeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionIdentifier {
            get {
                return this.transactionIdentifierField;
            }
            set {
                this.transactionIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionRecordNumber {
            get {
                return this.transactionRecordNumberField;
            }
            set {
                this.transactionRecordNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNumberSignature {
            get {
                return this.orderNumberSignatureField;
            }
            set {
                this.orderNumberSignatureField = value;
            }
        }
        
        /// <remarks/>
        public PaymentStatusEnum PaymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PaymentStatusEnum {
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OrderInfo {
        
        private string senderIPAddressField;
        
        private string orderNumberField;
        
        private string invoiceIDField;
        
        /// <remarks/>
        public string SenderIPAddress {
            get {
                return this.senderIPAddressField;
            }
            set {
                this.senderIPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentDetails {
        
        private double amountField;
        
        private CurrencyType currencyField;
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public CurrencyType Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CurrencyType {
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        EUR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitPaymentCompletedEventHandler(object sender, SubmitPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PaymentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PaymentResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void IsCreditCardValidCompletedEventHandler(object sender, IsCreditCardValidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCreditCardValidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCreditCardValidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CCValidationResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CCValidationResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TestSubmitPaymentCompletedEventHandler(object sender, TestSubmitPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestSubmitPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestSubmitPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591