using Microsoft.VisualBasic;
using SSW;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Collections.Specialized;
using System.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Caching;
using System.Web.SessionState;
using System.Web.Security;
using System.Web.Profile;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




public partial class ContactUs
{

	///<summary>
	///SiteMapPath1 control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.SiteMapPath SiteMapPath1;
	///<summary>
	///contactName control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlInputText contactName;
	///<summary>
	///RFV_contactName control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.RequiredFieldValidator RFV_contactName;
	///<summary>
	///contactEmail control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlInputText contactEmail;
	///<summary>
	///RFV_contactEmail control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.RequiredFieldValidator RFV_contactEmail;
	///<summary>
	///REV_contactEmail control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.RegularExpressionValidator REV_contactEmail;
	///<summary>
	///contactPhone control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlInputText contactPhone;
	///<summary>
	///RFV_contactPhone control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.RequiredFieldValidator RFV_contactPhone;
	///<summary>
	///MailMessageFreeTextBox control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.HtmlControls.HtmlTextArea MailMessageFreeTextBox;
	///<summary>
	///RFV_contactMessage control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.RequiredFieldValidator RFV_contactMessage;
	///<summary>
	///cboTimeZone control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::System.Web.UI.WebControls.DropDownList cboTimeZone;
	///<summary>
	///btnSend control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	private global::System.Web.UI.WebControls.Button withEventsField_btnSend;
	protected global::System.Web.UI.WebControls.Button btnSend {
		get { return withEventsField_btnSend; }
		set {
			if (withEventsField_btnSend != null) {
				withEventsField_btnSend.Click -= btnSend_Click;
			}
			withEventsField_btnSend = value;
			if (withEventsField_btnSend != null) {
				withEventsField_btnSend.Click += btnSend_Click;
			}
		}

	}
	///<summary>
	///OpenTimeOfficeHours control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>

	protected global::SSW.Website.WebUI.Components.OpenTime OpenTimeOfficeHours;
	///<summary>
	///OpenTimeAfterHours control.
	///</summary>
	///<remarks>
	///Auto-generated field.
	///To modify move field declaration from designer file to code-behind file.
	///</remarks>
	protected global::SSW.Website.WebUI.Components.OpenTime OpenTimeAfterHours;
}
