//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("ServiceUri=https://sswstaging.crmdev2015.ssw.com.au/SSWStaging; Domain=SSW2000; A" +
            "uthType=IFD; UserName=SSW2000\\AdminLuZhang; Password=7Welcome; LoginPrompt=Never" +
            ";")]
        public string CrmConnectionStringTesting {
            get {
                return ((string)(this["CrmConnectionStringTesting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("ServiceUri=https://live.crm.ssw.com.au/Live; Domain=SSW2000; AuthType=IFD; UserNa" +
            "me=SSW2000\\CrmTimeProSync; Password=eeGKSD7F4HrCCscZDmMw!; LoginPrompt=Never;")]
        public string CrmConnectionStringProduction {
            get {
                return ((string)(this["CrmConnectionStringProduction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@ssw.com.au")]
        public string UnsubscribeNotificationRecipient {
            get {
                return ((string)(this["UnsubscribeNotificationRecipient"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("info@ssw.com.au")]
        public string UnsubscribeNotificationSender {
            get {
                return ((string)(this["UnsubscribeNotificationSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6B04BB29-BEED-E611-80D4-00155D01225D")]
        public string TagIdProduction {
            get {
                return ((string)(this["TagIdProduction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4DAA0AE3-BEED-E611-80DF-00155D01CD29")]
        public string TagIdTesting {
            get {
                return ((string)(this["TagIdTesting"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugEnabled {
            get {
                return ((bool)(this["DebugEnabled"]));
            }
        }
    }
}
