<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet xmlns:ssw="urn:schemas-ssw-com-au:xslt" xmlns:msxsl="urn:schemas-microsoft-com:xslt" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

<xsl:param name="MakeHtmlHeader" />

<xsl:template match="/XMLDATA">
	<xsl:if test="$MakeHtmlHeader = 'True'"><xsl:call-template name="Header" /><xsl:call-template name="Styles" /></xsl:if>
	
	<p>Dear Web Master,</p>
	
	<p>
		There are <b><xsl:value-of select="@FailedRules" /></b> &quot;failed&quot; rules for this job.<br />
		There are <b><xsl:value-of select="@FailedFiles" /></b> &quot;failed&quot; files for this job.<br />
		There are <b><xsl:value-of select="@ErrorsMatched" /></b> errors matched.<br />
	</p>
	
	<p>
		The full report is attached.
	</p>
	
	<p>Please investigate the cause of these failures and allocate fixing tasks.</p>
	
	<p>
		You may request a link scan by terminal service into Hippo, and run Code Auditor from the Start Menu.<br />
	</p>
	
	<table>
		<tr>
			<td>LinkScan Started:</td>
			<td><xsl:value-of select="@StartTime" /></td>
		</tr>
		<tr>
			<td>LinkScan Ended:</td>
			<td><xsl:value-of select="@EndTime" /></td>
		</tr>
		<tr>
			<td>Time Taken:</td>
			<td><xsl:value-of select="@TimeTaken" /></td>
		</tr>
		<tr>
			<td>Files Processed:</td>
			<td><xsl:value-of select="@FilesProcessed" /></td>
		</tr>
		<tr>
			<td>Total Files:</td>
			<td><xsl:value-of select="@FileCount" /></td>
		</tr>
	</table>
	
	<br/>

	<div id="footer">
		<div style="background-color: whitesmoke">Generated By SSW.CodeAuditor</div>
	</div>
	
	<br />
	
	<xsl:if test="$MakeHtmlHeader = 'True'"><xsl:call-template name="Footer" /></xsl:if>
</xsl:template>
		



<!-- HTML Header-->

<xsl:template name="Header">
<xsl:text disable-output-escaping="yes">
<![CDATA[

<html>
	<head>
		<meta name="GENERATOR" content="Microsoft Visual Studio 7.0">
		<title>SSW Code Auditor Scan Report</title>
	</head>
	<body>
]]>
</xsl:text>
</xsl:template>





<!-- HTML Footer -->

<xsl:template name="Footer">
<xsl:text disable-output-escaping="yes">
<![CDATA[

		<table class="MsoNormalTable" border="0" cellpadding="0" width="100%" style='width:100.0%' ID="Table1">
			<tr height="17" style='height:12.75pt'>
				<td height="17" bgcolor="#FF0033" style='background:#FF0033;padding:1.5pt 1.5pt 1.5pt 1.5pt; height:12.75pt'>
					<p class="MsoNormal"><font size="3" face="Times New Roman"><span style='font-size:12.0pt'>&nbsp;</span></font></p>
				</td>
			</tr>
		</table>
		<table class="MsoNormalTable" border="0" cellpadding="0" width="100%" style='width:100.0%' ID="Table2">
			<tr height="19" style='height:14.25pt'>
				<td height="19" bgcolor="#CCCCCC" style='background:#CCCCCC;padding:1.5pt 1.5pt 1.5pt 1.5pt;
			height:14.25pt'>
					<p class="MsoNormal"><strong><b><font size="2" face="Verdana"><span style='font-size:10.0pt;font-family:Verdana'>Superior Software for Windows</span></font></b></strong><font size="2" face="Verdana"><span style='font-size:10.0pt;font-family:Verdana'>
			Custom Software Solutions in ASP.NET, VB.NET, SQL Server, Exchange and MS
			Access </span></font></p>
				</td>
			</tr>
		</table>
		<ul type="disc">
			<li class="MsoNormal">
				<font size="2" face="Verdana">
					<span style='font-size:10.0pt;
				font-family:Verdana'>Check out our HOT utilities for VB and .NET
				Developers <a href="http://www.ssw.com.au/">www.ssw.com.au</a> </span></font></li>
			<li class="MsoNormal">
				<font size="2" face="Verdana">
					<span style='font-size:10.0pt;
				font-family:Verdana'>Keep up-to-date at the .NET User Group, </span></font><font size="2" face="Verdana"><span style='font-size:10.0pt;font-family:Verdana'>Sydney</span></font><font size="2" face="Verdana"><span style='font-size:10.0pt;font-family:Verdana'>
						<a href="http://www.ssw.com.au/NETUG">www.ssw.com.au/NETUG</a>
					</span></font></li>
		</ul>
	</BODY>
</HTML>

]]>
</xsl:text>
</xsl:template>



<!-- Stylesheets -->

<xsl:template name="Styles">
	<style type="text/css">
		P
		{
			font: 9pt Verdana;
		}
		
		#footer
		{
			font: 9pt Verdana;
			border-top: 1px solid black;
			line-height: 13pt;
		}
		
		#footer DIV
		{
			padding: 3px;
		}
		
		#footer A
		{
			color: darkblue;
		}
		
		TABLE TD
		{
			font: 9pt Verdana;
			padding: 3px;
		}
		
		H1
		{
			font: 15pt Verdana;
			color: silver;
		}
	</style>
</xsl:template>



<msxsl:script implements-prefix="ssw" language="csharp">
<![CDATA[
/*
string timeToWord(string srcTime)
{
	string sReturn = "";
	int iHour, iMin, iSec;
	
	iMin = (int) float.Parse(srcTime);
	iHour = (int) (iMin / 60);
	iSec = (int) Math.Round((float.Parse(srcTime) - iMin) * 60);
	iMin %= 60;
	
	return iSec.ToString();
	
	if (iHour != 0)
		sReturn += iHour.ToString() + " hours ";
	if (iHour != 0 && iMin != 0)
		sReturn += iMin.ToString() + " minute ";
	sReturn += iSec.ToString();
	
	return sReturn;
}
*/
]]>
</msxsl:script>


</xsl:stylesheet>