<%@ Page Language="VB" MasterPageFile="~/Masters/Default.master" AutoEventWireup="false" Title="SSW .netTiers Suggestions"  %>

<asp:content ID="Content1" ContentPlaceHolderID="mainContentPlaceHolder" runat="server">
    <p>        
	    <asp:SiteMapPath ID="SiteMapPath1" runat="server" SiteMapProvider="SSWStandardsXmlSiteMapProvider">
        </asp:SiteMapPath>
    </p>
    <asp:label id="lblWelcome" runat="server"></asp:label>
    <p>.netTiers is a set of open source code templates used in CodeSmith for object-relational mapping. It automatically generates a personnalized Data Tiers application (on a base of a SQL Server Database) in just a few minutes.</p>
    <p>With the application it generated, you can manage data of a web application easily and efficiently. So It's a good tool for <a href="/ssw/Standards/Rules/RulesToBetterWebsitesTuningAndMaintenance.aspx">Website Maintenance</a>.</p>
    <p>In order to make it better, following points may help.</p>    
    <p>Do you agree with them all? Are we missing some? <a href="/ssw/Company/ContactUs.aspx">contact us</a> with what you think.
    </p>
    <table class="clsSSWTableOfContents" cellspacing="2" cellpadding="2" summary="Index" align="right" style="{width:100%;}">
	    <tr> 
  		    <td> 
			    <ol>				
				    <li><a href="#EntityName">Add prefix before entity name</a></li>
				    <li><a href="#DualKeys">Relate to a dual primary keys table</a></li>
				    <li><a href="#SupportPicture">Make it support pictures (binary fields)</a></li>
				    <li><a href="#LinkToChildren">Support links to the child table, e.g. the OrderDetails table</a></li>
				    <li><a href="#UseAJaxDatePicker">Change Date fields to use the normal MS AJAX date picker</a></li>
				    <li><a href="#AddBreadcrumb">Add breadcrumbs (especially for child tables)</a></li>
				    <li><a href="#DisableAddNew">When you click 'Edit', please disable the 'Add New' button</a></li>
				    <li><a href="#UseCommandLine">Encourage people to use the command line to run the generation</a></li>
			    </ol>			
			    <br/>
		    </td>
	    </tr>
    </table>
	<ol>	
	    <li>
	        <a name="EntityName"></a><H2>Add prefix before entity name</h2>
		    <p>
		    Entities generated by NetTiers have the same names as their corresponding database tables. However, if the table name is equal to one of .Net Framework classes, 
		    e.g. Timezone, Visual Studio might raise compile errors. Because auto-generated namespace and System namespace are included and Visual Studio can't identify which namespaces the class should belong to.
		    As a result, users have to revise the compile errors one by one. If the entity name is combined a prefix with the table name, most of the compile errors must be disappeared.  
		    </p>
	    </li>
	    <li>
	        <a name="DualKeys"></a><H2>Relate to a dual primary keys table</h2>
		    <p>
		    It is such a complex work to collect all the relationships in NetTiers - one to one, one to many, many to many. If the table relationships are nested, the grid in the auto-generated page might be bound to a wrong data source.<br />
		    For example, there are 3 tables A, B and C. A has a primary key named 'KeyA', which is B's foreign key. B has a dual primary key 'KeyA' and 'KeyB'. C has a relationship with B based on 'KeyA' and 'KeyB'. 
		    In this condition, the databinding of C's page is incorrect.  
		    </p>
	    </li>	    
        <li><a name="SupportPicture"></a><h2>Make it support pictures (binary fields)</h2>
        <p>The 'Picture' field is not rendered but a text 'System.byte[]' takes the place. </p>
        <dl class="image"> 
            <dt><img alt="'Picture' field not rendered properly" src="/ssw/Standards/BetterSoftwareSuggestions/Images/SupportPicture1.JPG" /></dt>
            <dd>Figure: 'Picture' field not rendered properly</dd>
        </dl>
        <p>When I click 'Edit' button and then click 'Update' button, I got an error. Because the Text 'System.Byte[]' was bound to Image field.</p>
        <dl class="image"> 
            <dt><img alt="Error of updating Image Field" src="/ssw/Standards/BetterSoftwareSuggestions/Images/SupportPicture2.JPG" /></dt>
            <dd>Figure: Error of updating Image Field</dd>
        </dl>
        <p>Moreover, when I want to add a new category, I cannot add a picture for it (e.g., select a picture and upload it).</p>
        <dl class="image"> 
            <dt><img alt="Can not add pictures" src="/ssw/Standards/BetterSoftwareSuggestions/Images/SupportPicture3.JPG" /></dt>
            <dd>Figure: Can not add pictures</dd>
        </dl> 
        <p>So please make it support pictures (view, add and update).</p>
        </li>
        <li><a name="LinkToChildren"></a><h2>Support links to the child table, e.g. the OrderDetails table</h2>
        <p>It will be wonderful if there're links to child tables. For instance, sometimes I'd like to see order detail items of the first order just by clicking a link rather than go to OrderDetails page and search items with the order id.</p>
        <dl class="image"> 
            <dt><img alt="Add links to child table" src="/ssw/Standards/BetterSoftwareSuggestions/Images/SupportLinks.JPG" /></dt>
            <dd>Figure: Add links to child table</dd>
        </dl> 
        </li>
        <li><a name="UseAJaxDatePicker"></a><h2>Change Date fields to use the normal MS AJAX date picker</h2>
        <p>This would be good because we would always get the AJAX library included by default.</p>
        <dl class="image"> 
            <dt><img alt="Change Date fields to MS AJAX date picker" src="/ssw/Standards/BetterSoftwareSuggestions/Images/DateFieldChange.JPG" /></dt>
            <dd>Figure: Change Date fields to MS AJAX date picker</dd>
        </dl>
        </li>
        <li><a name="AddBreadcrumb"></a><h2>Add breadcrumbs (especially for child tables)</h2>
        <p>Without a breadcrumb, it's not convenient to go to previous pages and we don't know where exactly we are.</p>
        <p>Please add breadcrumbs, especially for child tables. E.g., Home &gt; Orders &gt Order 123</p>
        <dl class="image"> 
            <dt><img alt="No Breadcrumb" src="/ssw/Standards/BetterSoftwareSuggestions/Images/AddBreadcrumb.JPG" /></dt>
            <dd>Figure: No Breadcrumb</dd>
        </dl>
        </li>
        <li><a name="DisableAddNew"></a><h2>When you click 'Edit', please disable the 'Add New' button</h2>
        <p>When you click 'Edit' button, you are going to edit a record. However 'Add New' button is still available. This is not proper.</p>
        <p>Please disable 'Add New' button when it's in Edit mode.</p>
        <dl class="image"> 
            <dt><img alt="'Add New' button is still available in Edit mode" src="/ssw/Standards/BetterSoftwareSuggestions/Images/DisableAddNew.JPG" /></dt>
            <dd>Figure: 'Add New' button is still available in Edit mode</dd>
        </dl>
        </li>
        <li><a name="UseCommandLine"></a><h2>Encourage people to use the command line to run the generation</h2></li>
        <p>When the generation is completed, it's better to encourage people to use a command line to do this generation as per rule <a href="/ssw/Standards/rules/rulestobetterwindowsforms.aspx#CodeGenerators">Do you use code generators</a>.</p>
        <p>E.g.,</p> 
        <dl class="code">
            <dt>
            <pre>Tip: The command line to run this generation again is 'cs D:\DataDavidBian\Personal\New12345\NetTiers.csp'.
You can also put this command in a Batch file (e.g., _Regenerate.bat) and double click it.</pre>
            </dt>
        <dd>Figure: How to encourage people to user command line</dd>
        </dl>
        <p>With this command line, people do not bother to follow those steps to make this generation next time, instead just run the command line and the whole generation will be completed automatically. See our <a href="http://rules.ssw.com.au/SoftwareDevelopment/RulesToBetterDotNETProjects/Pages/RegenerateStandard.aspx">regenerate standard</a>.</p>
        <dl class="image"> 
            <dt><img alt="Generation completed" src="/ssw/Standards/BetterSoftwareSuggestions/Images/CommandLine.jpg" /></dt>
            <dd>Figure: Generation completed</dd>
        </dl>
	</ol>
    <h2>Acknowledgements</h2>
        <p>
            <a href="/ssw/Employees/EmployeesProfile.aspx?EmpID=AC">Adam Cogan</a><br />    
	    </p>
</asp:content>