<%@ Page Language="VB" MasterPageFile="~/Masters/Default.master" AutoEventWireup="false"
    Title="SSW Telerik Test Suite Suggestions" %>

<%@ Register TagPrefix="ssw" TagName="RandomTestimonial" Src="~/Components/RandomTestimonial.ascx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="mainContentPlaceHolder" runat="server">
    <p>
        <asp:SiteMapPath ID="SiteMapPath1" runat="server" SiteMapProvider="SSWStandardsXmlSiteMapProvider">
        </asp:SiteMapPath>
    </p>
    <ssw:RandomTestimonial ID="testimonial" runat="server" Display="TopCommon" CategoryID="10" />
    <br />
    <p>
        Do you agree with them all? Are we missing some? <a href="javascript:sendEmail('6D61696C746F3A696E666F407373772E636F6D2E61753F5375626A6563743D52756C6573253230746F253230426574746572253230536574757073')">
            Let us know</a> what you think.</p>
    <div class="TableOfContents">
        <ol>
            <li><a href="#XML">Help me know I should not be looking at XML</a></li>
            <li><a href="#FigureOutActions">Help me figure out that the 10 actions do </a></li>
            <li><a href="#NoticeInfo">Help me understand what action will do before I click an 'Add' button</a></li>
            <li><a href="#CompleteTestMenu">Telerik Web Test - Complete the Telerik menu</a></li>
            <li><a href="#BoldDefault">Telerik Web Test - Bold the default</a></li>
            <li><a href="#DeleteAll">Telerik WPF Test - Help me know it will delete all (little one)</a></li>
            <li><a href="#OtherWPFApps">Telerik WPF Test - Help me know other WPF apps I have installed</a></li>
            <li><a href="#ProgressOfTheRun">Help me know the progress of the run (aka where it is up to) in the grid</a></li>
            <li><a href="#WrongCodeIcon">Change the code icon to the VB code</a></li>
            <li><a href="#OutOfTheBox">Help me have a better out of the box experience </a></li>
            <li><a href="#ImproveBrand">Improve Branding in Chrome </a></li>
            <li><a href="#SideBySide">Open side by side (so you can see the steps as you record) </a></li>
            <li><a href="#SameOrder">Run the tests in the same order </a></li>
            <li><a href="#ImageVerification">Help me have Image Verification work on first attempt</a></li>
            <li><a href="#HelpMenu">Telerik Tests - Help menu </a></li>
            <li><a href="#DebugPopupWindow">Improve the 'Debug' Popup Window  </a></li>
            <li><a href="#ClickDom">When you click the DOM explorer nothing happenes </a></li>
            <li><a href="#InsertManualStep">Help me insert a manual step - give me another action 'Insert Manual Step' </a></li>
            <li><a href="#Databinding">Help me know I have hooked up databinding </a></li>
            <li><a href="#NiceBranding">Add some nice Telerik Branding</a></li>
            <li><a href="#DragAction">Help me know where my drag actions (inside an IF) are going </a></li>
            <li><a href="#RightClickForMenu">Help me use Right click for menu (not to save)</a></li>
            <li><a href="#ReadLinks">Help me read the links as they appear on the page</a></li>
            <li><a href="#DeleteIcon">Help me find Delete faster</a></li>
            <li><a href="#AboutMissing">Help | About missing</a></li>
            <li><a href="#TooltipsOnDragging">Tooltips needed on dragging</a></li>
            <li><a href="#MoveLogLink">Move the 'Log' hyperlink to be more logic spot (based on order of the actual sequence)</a></li>
            <li><a href="#HighlightChanges">Help me (when I am recording) know what I just did, highlight what I just added</a></li>
            <li><a href="#RecordingTest">Telerik Tests - start recording </a></li>
            <li><a href="#TextCopyBug">BUG - cant copy the text</a></li>
            <li><a href="#MoreReadable">Little one - more readable for entering text </a></li>
            <li><a href="#HighlightAction">Help me (when I am recording) know what I just did, highlight what I just added </a></li>
            <li><a href="#AutoGeneratedDocumentation">Great Idea - Auto generated training documentation!!!</a></li>
            <li><a href="#RightClickIgnoreThese">Web Tests &#8211; Add Right Click 'Ignore these'</a></li>
        </ol>
    </div>
    <div id="mainContent">
        <ol>
            <li>
                <h2><a name="XML"></a>Help me know I should not be looking at XML</h2>
                <p>
                  Add a XML comment e.g.<br/>
                  
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;!--   To view this in a GUI use 'Telerik Test Studio Developer Edition'      --&gt;<br />
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;!--                                                                          --&gt;
                </p>
                <p>
                  PS: I hate having 2 test products from Telerik to choose to install. I want a smaller/cheaper one and the larger/everything one<br />
                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I like working from an exe (and from VS secondary)<br />
                      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This is why I choose to install the wrong one.
                </p>
                <dl class="image">
                    <dt><img src="Images/InstallAnEditor.JPG" alt="There is an editor to install."/></dt>
                    <dd>Figure: Tell me there is an editor to install</dd>
                </dl>
            </li>

            <li>
              <h2><a name="FigureOutActions"></a>Help me figure out that the 10 actions do</h2>
              <p>I can't quickly figure out that these 10 options do.</p>
                   <dl class="image">
                    <dt>
                        <img src="Images/HoverOverInfo.JPG" alt="The info appears when you hover over the options. "/></dt>
                    <dd>
                        Figure: I want to hover over each option and see more info - See example on the web page below  <a href="http://www.ssw.com.au/ssw/events/Scrum-Training-Course.aspx">http://www.ssw.com.au/ssw/events/Scrum-Training-Course.aspx</a> </dd></dl>
               <p>I strongly believe if the team adds a decent sized image, it will make a world of difference. especially to the first experience when you really don't know what to do.</p>
            </li>

            <li>
              <h2><a name="NoticeInfo"></a>Help me understand what action will do before I click an 'Add' button</h2>
                 <dl class="image">
                    <dt><img src="Images/GoodExperience.JPG" alt="A great experience. "/></dt>
                    <dd>Figure: This was a great experience</dd>
                </dl>
                <ol>
                    <li>Change "OK" to "Add"</li>
                    <li>Add this UI to the first one "Project Elements" then I would have known what it was doing</li>
                    <li>Consider it for all 10 actions on the upside down iPhone!</li>                  
                </ol>
            </li>

            <li>
             <h2><a name="CompleteTestMenu"></a>Telerik Web Test - Complete the Telerik menu</h2>
               <dl class="image">
                    <dt><img src="Images/CompleteMenu.JPG" alt="Complete Menu"/></dt>
                    <dd>Figure: These 2 should be on the Telerik menu (and I would get rid of that toolbar)</dd>
               </dl>            
            </li>
               
            <li>
                <h2><a name="BoldDefault"></a>Telerik Web Test - Bold the default</h2>
                <dl class="image">
                    <dt><img src="Images/BoldOption.JPG" alt="Bold option "/></dt>
                    <dd>Figure: one of these 3 should be bold - I believe it should be the 2nd one 'Launch new Recording Browser'</dd>
                </dl>            
            </li> 

            <li>
                <h2><a name="DeleteAll"></a>Telerik WPF Test - Help me know it will delete all (little one)</h2>
                <p>I am a goose, I thought it was going to delete 1. </p>
                <p>Either change</p>
                <ul>
                    <li>"all" to "*all*", or</li>
                    <li>"all" to "all 4"</li>              
                </ul>
                <dl class="image">
                    <dt><img src="Images/MentionNumber.JPG" alt="Mention the No. "/></dt>
                    <dd>Figure: I would like it to mention the number of records to be deleted</dd>
                </dl> 
            </li>

            <li>
                <h2><a name="OtherWPFApps"></a>Telerik WPF Test - Help me know other WPF apps I have installed</h2>
                <p>I think it is cool that you tell me other running WPF apps.<br />
                I would love a button "Find other installed WPF apps you have"\
                </p>
                <dl class="image">
                    <dt><img src="Images/WPFApps.JPG" alt="WPF Apps against Telerik "/></dt>
                    <dd>Figure: I would like to know other WPF apps I can use Telerik Test against</dd>
                </dl> 
            </li> 
             
            <li>
                <h2><a name="ProgressOfTheRun"></a>Help me know the progress of the run (aka where it is up to) in the grid</h2>
                <p>Add the tick or cross in the VS window as the test is executing </p>
                <dl class="image">
                    <dt><img src="Images/AddGreenIcons.JPG" alt="Add green icons to the tests "/></dt>
                    <dd>Figure: Can you add a green icon 'Pass' as each test is passed. Ideally use the same icons as Microsoft Test Manager</dd>
                </dl> 
            </li>
               
            <li>
                <h2><a name="WrongCodeIcon"></a>Change the code icon to the VB code</h2>
                <dl class="image">
                    <dt><img src="Images/ChangeCodeIcon.JPG" alt="Change the code icon "/></dt>
                    <dd>Figure: Change the code icon to the VB code + use the icon on the dialog</dd>
                </dl> 
            </li>

            <li>
                <h2><a name="OutOfTheBox"></a>Help me have a better out of the box experience </h2>
                <p>Demoing Teleriks Work Item Manager *is easy* </p>
                <p>Just create a new TFS Team Project in VS.NET and show this stuff<br />
                <a href="http://www.telerik.com/products/tfsmanager-and-tfsdashboard/tfs-work-item-manager-features.aspx">http://www.telerik.com/products/tfsmanager-and-tfsdashboard/tfs-work-item-manager-features.aspx</a> </p>
                <p>However, demoing their Project Portal is *not* easy.</p>
                <p>Anyone got any tips (or word scripts) that you follow (after creating a team project). That shows you what data (code to add, Builds to add etc) to enter, so you can explain all the bits that the Telerik Project Portal will show</p>
                <dl class="image">
                    <dt><img src="Images/ProjectPortalIssue.JPG" alt="Project portal issue"/></dt>
                    <dd>Figure: The Project Portal does not look so create on a brand new TFS 2010 Team Project</dd>
                </dl> 
                <dl class="image">
                    <dt><img src="Images/ProjectConfigurationIssue.JPG" alt="Project Configuration Issue "/></dt>
                    <dd>Figure: Out of the box experience doesn't have the 'Code Churn' and 'Code Coverage' setup</dd>
                </dl>        
                <p>PS: I wish TFS had an option "Create a sample Northwind Team Project "</p>          
            </li>

            <li>
                <h2><a name="ImproveBrand"></a>Improve Branding in Chrome</h2>
                <dl class="badImage">
                    <dt><img src="Images/MentionInWebUI.JPG" alt="Mention Telerik in WebUI name "/></dt>
                    <dd>Figure: Bad example &#8211; add "Telerik" to the WebUI name</dd>
                </dl>   
                <dl class="goodImage">
                    <dt><img src="Images/VendorMentioned.JPG" alt="The vendor's name has been mentioned. "/></dt>
                    <dd>Figure: Good example - In Firefox 4, I see where these Testing Frameworks come from - since "Telerik" is mentioned</dd>
                </dl>   
            </li>

            <li>
                <h2><a name="SideBySide"></a>Open side by side (so you can see the steps as you record)</h2>
                <p>This is more consistent with CodedUI tests (but a little different).</p>
                <dl class="image">
                    <dt><img src="Images/SideBySide.JPG" alt="Open side by side like this "/></dt>
                    <dd>Figure:Open side by side like this (both windows are restored and 3/4 screen size)</dd>
                </dl>              
            </li>

            <li>
                <h2><a name="SameOrder"></a>Run the tests in the same order </h2>
                <dl class="image">
                    <dt><img src="Images/RunTest.JPG" alt="run the test in the same order "/></dt>
                    <dd>Figure:Run the tests in the same order</dd>
                </dl>               
            </li>
            
            <li>
                <h2><a name="ImageVerification"></a>Help me have Image Verification work on first attempt</h2>
                    <p>Here is the default experience:</p>
                    <dl class="image">
                        <dt><img src="Images/ImageVerification.jpg" alt="record an Image Verification verification"/></dt>
                        <dd>Figure: I record an "Image Verification" verification</dd>
                    </dl>
                    <dl class="image">
                        <dt><img src="Images/ImageVerificationRun.jpg" alt="run an Image Verification verification"/></dt>
                        <dd>Figure: I run it</dd>
                    </dl>
                    <p>Image verification failed. Image difference is '40.86%' which is more than the allowed error tolerance of ' 1.00%'.</p>
                    <dl>
                        <dt class="greyBox" style="color:Red;">Image verification failed. Image difference is '40.86%' which is more than the allowed error tolerance of '1.00%'.</dt>
                        <dd>Figure: I get an error of 40%</dd>
                    </dl>
                    <dl class="image">
                        <dt><img src="Images/ImageVerificationError.jpg" alt="Image Verification error "/></dt>
                        <dd>Figure: I see defails of the error... I think...mmmm maybe the images are different because it was not in full screen</dd>
                    </dl>
                    <h3>Suggestion 1</h3>
                    <p>Image verification failed. Image difference is '40.86%' which is more than the allowed error tolerance of '1.00%'.</p>
                    <p><strong>More Information:</strong></p>
                    <p>Check the test ran in Full Screen</p>
                    <dl>
                        <dt class="greyBox" style="color:Red;">Image verification failed. Image difference is '40.86%' which is more than the allowed error tolerance of '1.00%'.<br /><br />
                        More Information:<br />
                        Check the test ran in Full Screen
                        </dt>
                        <dd>Figure: Improve the error to have this 'More Information'</dd>
                    </dl>
                    <h3>Suggestion 2</h3>
                    <dl class="image">
                        <dt><img src="Images/ImageVerificationRun.jpg" alt="Image Verification More Info"/></dt>
                        <dd>Figure: When you run 'Quick Execute' always put it in full screen</dd>
                    </dl>
            </li>

            <li>
                <h2><a name="HelpMenu"></a>Telerik Tests - Help menu</h2>
                <p>Do I have any complaint about their Help menu?<br />
                    If so please action<br />
                    If not please tell me to give you the text because it does not have the version (amazing)
                </p>
                <dl class="image">
                    <dt><img src="Images/MissingVersionNumber.jpg" alt="Missing version number "/></dt>
                    <dd>Figure: Missing version number</dd>
                </dl>
            </li>

            <li>
                <h2><a name="DebugPopupWindow"></a>Improve the 'Debug' Popup Window </h2>
                <p>2 little things could help give a nicer experience:</p>
                <ul>
                    <li>There are 3 buttons are disabled here. It is not clear enough</li>
                    <li>Add a "Stop" button. I desire to hit a "Stop" button, so I can add an extra step. I am confused if there is a reason I can't do this.</li>              
                </ul>
                <dl class="image">
                    <dt><img src="Images/DisabledButton.jpg" alt=" How may disabled button are here?"/></dt>
                    <dd>Figure: How may disabled button are here?</dd>
                </dl>
            </li>

            <li>
                <h2><a name="ClickDom"></a>When you click the DOM explorer nothing happenes</h2>
                <ol>
                    <li>When you click the DOM explorer icon, open the right hand nav bar.</li>
                    <li>Explain why it is useful. Change the hover text from<br />
                        "Locate in DOM explorer"<br />
                        to<br />
                        "Locate in DOM explorer. This is useful to see the parent or child controls for example xxxxxx"
                    </li>
                    <li>Add the same DOM icon - over onto the right navigation title bar - so you have some visual association.</li>              
                </ol>
                <dl class="image">
                    <dt><img src="Images/ClickTheDomResult.jpg" alt="Result of clicking the dom"/></dt>
                    <dd>Figure: Clicking the DOM explorer icon does nothing (when the right nav is closed) </dd>
                </dl>
            </li>

            <li>
                <h2><a name="InsertManualStep"></a>Help me insert a manual step  - give me another action 'Insert Manual Step'</h2>
                <dl class="image">
                    <dt><img src="Images/InsertManualStep.jpg" alt="Insert manual step "/></dt>
                    <dd>Figure: Give me another action 'insert manual step' </dd>
                </dl>
                <dl class="image">
                    <dt><img src="Images/NoNeedGoBack.jpg" alt="No need go back "/></dt>
                    <dd>Figure:So I don't need to go back to Test Studio  </dd>
                </dl>
                <p>PS: Also help me know how cool 'manual steps' are <br />
                Add some tooltip text that talks about what a great feature this is. E.g.</p>
                <div class="greyBox">
                    <p>
                        Manual Steps are very useful to enable Developers and Testers to work together during a sprint.<br />
                        The goal of a successful sprint (if you are doing Scrum) is to have the sprint fully tested by the end of the sprint. <br /><br />

                        Normally this is hard, but not with 'Manual Steps'.<br /><br />

                        Insert a 'Manual Step' to enable you to have a tests for incomplete User Stories.<br />
                        Say you have the major items complete, such as the first and last part of the User story is working (but something is missing in the middle - eg. the status field needs to be manually set) then insert a 'Manual Test' with text such as:<br />
                        'Now manually update the status field. Joe will be making this automatic later.'
                    </p>
                </div>
            </li>

            <li>
                <h2><a name="Databinding"></a>Help me know I have hooked up databinding</h2>
                <dl class="image">
                    <dt><img src="Images/StrukThroughText.jpg" alt="Struck through the text "/></dt>
                    <dd>Figure: Make the text struck through when data binding is successfully hooked up (I was incorrectly assuming I had not hooked it up)</dd>
                </dl>
            </li>

            <li>
                <h2><a name="NiceBranding">Add some nice Telerik Branding</a></h2>
                <dl class="image">
                    <dt><img src="Images/AddSthMore.jpg" alt="Add sth. more and branding + logo "/></dt>
                    <dd>Figure: Add "Please wait" Add Green Telerik Branding + Logo</dd>
                </dl>
                <p>Then after we connect it looks like:</p>
                <dl class="image">
                    <dt><img src="Images/RemoveOverPoweringText.jpg" alt="Remove the over powering text "/></dt>
                    <dd>Figure: Add Green Telerik Branding + Logo... remove the bold on the 5 arrow text (it is over powering) </dd>
                </dl>            
            </li>
            
            <li>
                <h2><a name="DragAction">Help me know where my drag actions (inside an IF) are going</a></h2>
                <p>When I drag it into the IF</p>
                <ol>
                    <li>I want you to pop a dialog telling me the 3 different options
                        <ul>
                            <li>put it *before* the IF</li>
                            <li>put it *inside* the IF</li>
                            <li>put it *after* the IF</li>                 
                        </ul>
                         <dl class="image">
                            <dt><img src="Images/FourOptions.jpg" alt="4 options"/></dt>
                            <dd>Figure: This example from Excel lets the user know there is 4 options </dd>
                         </dl>  
                    </li>
                    <li>After selecting OK<br />
                        I want to see the current line selected like this (I thought I lost it)
                        <dl class="image">
                            <dt><img src="Images/AfterDrag.jpg" alt="After daraging experience"/></dt>
                            <dd>Figure: This is the experience I should get after dragging </dd>
                        </dl>  
                    </li>
             </ol>
             
            </li>

            <li>
                <h2><a name="RightClickForMenu">Help me use Right click for menu (not to save)</a></h2>
                <dl class="image">
                    <dt><img src="Images/RightClickMenu.jpg" alt="Right click menu with copy"/></dt>
                    <dd>Figure: When I right click it saves! When I right click now, please give me a right click menu with 'Copy'</dd>
                 </dl>  
            </li>

            <li>
                <h2><a name="ReadLinks">Help me read the links as they appear on the page</a></h2>
                <dl class="image">
                    <dt><img src="Images/ActualLinkText.jpg" alt="I like to read the actual link text."/></dt>
                    <dd>Figure: I would to read the actual link text e.g. Click 'NonSprite' link  </dd>
                </dl>  
                <dl class="image">
                    <dt><img src="Images/IndicateText.jpg" alt="Indication tasks"/></dt>
                    <dd>Figure: Also include some text to indicate where you found the name X0NonSpriteNonSpriteLink - I looked in the 'Original Source' and it was not there</dd>
                </dl>  
            </li>

            <li>
                <h2><a name="DeleteIcon">Help me find Delete faster</a></h2>
                <dl class="image">
                    <dt><img src="Images/MissingIcon.jpg" alt="Black cross"/></dt>
                    <dd>Figure: Use the normal black cross in both places</dd>
                </dl> 
                <dl class="image">
                    <dt><img src="Images/BlackCross.jpg" alt="Icon missing"/></dt>
                    <dd>Figure: This is the icon most tester would recognize</dd>
                 </dl> 
            </li>

            <li>
                <a name="AboutMissing"></a><h2>Help | About missing</h2>
                <p>I was looking for the version number &#8211; I expect to see <strong>Help | About</strong></p>
                <ol>
                    <li>Maybe in your case change "Manage" to "About and Licences"</li>
                    <li>Make title bar consistent eg. Change &#8220;Licence Management&#8221; to "About and Licences"</li> 
                </ol>
                <dl class="image">
                    <dt><img src="Images/about-dialog.jpg" alt="Icon missing"/></dt>
                    <dd>Figure: I don't expect to click "Manage" to find the About dialog</dd>
                 </dl>
            </li>

            <li>
                <a name="TooltipsOnDragging"></a><h2>Tooltips needed on dragging</h2>
                <dl class="image">
                    <dt><img src="Images/tooltips-on-dragging.jpg" alt="Icon missing"/></dt>
                    <dd>Figure: I like the drag feature... but need tooltips explaining each on (on hover)</dd>
                 </dl>
            </li>

            <li>
                <a name="MoveLogLink"></a><h2>Move the 'Log' hyperlink to be more logic spot (based on order of the actual sequence)</h2>
                <p>I like finishing a demo of telerik tests, with showing the log... It has the time taken... and is a nice thing for a tester to send in their 'done' email.</p>
                <p>In addition the Storyboard report is too hidden.</p>
                <p>Here is my suggestion to improve it:</p>
                <dl class="image">
                    <dt><img src="Images/move-log-link.jpg" alt="Move Log Link"/></dt>
                    <dd>Figure: Move it to the last record with this text "Success - 9 seconds - 4/4 passed - View Log  or  View Storyboard (HTML)"</dd>
                 </dl>

                <div class="greyBox">
                    <p>Note: If you don't like this suggestion, then just move the 'Log' link over to the left, to be next to the 'executed.' Word.</p>
                </div>

            </li>
            <li>
              <h2><a name="HighlightChanges"></a>Help me (when I am recording) know what I just did, highlight what I just added</h2>
              <p>
                For example here I added a 'verify textcontent?' Action <br />
                It would be great if it would highlight it in the 'steps' grid
              </p>
              <dl class="image">
                    <dt><img src="Images/HighlightChanges.jpg" alt="Highlight changes "/></dt>
                    <dd>Figure: When I do an action, can you select it like the above (it would help learning)</dd>
                 </dl>
            </li>
            <li>
              <h2><a name="RecordingTest"></a>Telerik Tests - start recording</h2>
              <p>When I add a test I expect it to start recording.<br />
                This is consistent with Web Tests (but I admit not with CodedUI tests)</p>
               <dl class="image">
                    <dt><img src="Images/UnwantedManipulate.jpg" alt="Unwanted manipulate "/></dt>
                    <dd>Figure: I should not have to click "Record" after creating a new Telerik Test </dd>
                 </dl>
            </li>
            <li>
              <h2><a name="TextCopyBug"></a>BUG - cant copy the text</h2>
            <p>Do you guys make a test to fix this bug :-)</p>
             <dl class="image">
                    <dt><img src="Images/CopyBug.jpg" alt="bug"/></dt>
                    <dd>Figure: BUG - I want to copy and Paste to Word</dd>
             </dl>          
            </li>
            <li>
              <h2><a name="MoreReadable"></a>Little one - more readable for entering text </h2>
             <dl class="image">
                    <dt><img src="Images/NeedMoreReadable.jpg" alt="Please make it more readable."/></dt>
                    <dd>Figure: This feels backwards</dd>
             </dl> 
             <p>It would read better if you changed it to <br />
                &nbsp;&nbsp;&nbsp;&nbsp;<b>Enter text 'adam' in 'PlaceHolderSearchAreaS3031AEBBInputKeywordText'</b>
             </p>
            </li>

            <li>
                 <h2><a name="HighlightAction"></a>Help me (when I am recording) know what I just did, highlight what I just added</h2>
                 <p>For example here I added a 'verify textcontent...' Action <br />
                    It would be great if it would highlight it in the 'steps' grid</p>
                 <dl class="image">
                    <dt><img src="Images/HighlightTheAction.jpg" alt="Highlight the action I just did. "/></dt>
                    <dd>Figure: When I do an action, can you select it like the above (it would help learning)</dd>
                 </dl> 
            </li>

            <li>
                <h2><a name="AutoGeneratedDocumentation"></a>Great Idea - Auto generated training documentation!!!</h2>
                <p>One of the problems software teams hate doing is writing end user documentation.</p>
                <p>Add this functionality and you have a shortcut way to do this.</p>
                <ul>
                    <li>Create a word doc or upload to a wiki</li>
                    <li>Add a button &#8220;Create Training.docx&#8221; or &#8220;Upload Training"</li>
                    <li>Allow customized notes to be added</li>
                </ul>
                <dl class="image">
                    <dt><img src="Images/AutoGeneratedDoc.jpg" alt="Add functionality to create user documentation screen"/></dt>
                    <dd>Figure: Add functionality to create user documentation</dd>
                </dl>
                <h4>More Information</h4>
                <p>The 'Export Storyboard as HTML Documentation' does part of what they want, but it is not ready for the User without editing.</p>
                <p>This is an example of it when recording CRM2011... before you hit images:</p>
                <dt class="image">
                    <dl><div class="greyBox">
                        <h1>Steps</h1>
                        <ol>
                            <li>Navigate to : '<a href="https://ssw.crm.ssw.com.au">https://ssw.crm.ssw.com.au'</a>'</li>
                            <li>Navigate to : '<a href="https://ssw.crm.ssw.com.au">https://ssw.crm.ssw.com.au '</a></li>
                            <li>Handle 'Logon' dialog.</li>
                            <li>Navigate to : '<a href="https://ssw.crm.ssw.com.au">http://ssw.crm.ssw.com.au/'</a></li>
                            <li>Navigate to : '<a href="https://ssw.crm.ssw.com.au/main.aspx">https://ssw.crm.ssw.com.au/main.aspx</a>'</li>
                            <li>Click 'ContactsNobrTag'</li>
                        </ol>
                    </div></dl>
                    <dd>Figure: This is not ready for the End User without editing</dd>
                </dt>
                <p>Basically they want:</p>
                <ul>
                    <li>Another text field on each test step called 'User Documentation'</li>
                    <li>Even better would be another view called 'Documentation' that had the images (like the StoryBoard view) + the 'User Documentation'</li>
                    <li>Ready for the user and re-generated in the Build process</li>
                    <li>An option to create a Wiki instead of the .html file</li>
                </ul>
                <p>For a possible example, see <a href="http://www.ssw.com.au/ssw/codeauditor/UserGuide.aspx">http://www.ssw.com.au/ssw/codeauditor/UserGuide.aspx</a> (Start at Step 3)</p>
            </li>

            <li>
                <h2><a name="RightClickIgnoreThese"></a>Web Tests &#8211; Add Right Click 'Ignore these'</h2>
                <p>When recording SharePoint 2010 pages you get a lot of noisy pages (that is just junk to look at).</p>
                <dl class="image">
                    <dt><img src="Images/tfs-tests-reduce-noise.jpg" alt="TFS Tests - reduce noise"/></dt>
                    <dd>Figure: Reduce Noise&#8230; Add right click menu that would hide all these</dd>
                </dl>
            </li>


        </ol>
    </div>
    <h2>Acknowledgments</h2>
    <p><a href="/ssw/Employees/EmployeesProfile.aspx?EmpID=AC">Adam Cogan</a><br /></p>
</asp:Content>
