//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace SSWWebServiceSubscribers {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubscribersSoap", Namespace="http://tempuri.org/MembershipStats/Subscribers")]
    public partial class Subscribers : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TotalSubscribersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveNewsletterEmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Subscribers() {
            this.Url = "http://webservices.internal.ssw.com.au/membershipstats/subscribers.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TotalSubscribersCompletedEventHandler TotalSubscribersCompleted;
        
        /// <remarks/>
        public event SaveNewsletterEmailCompletedEventHandler SaveNewsletterEmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MembershipStats/Subscribers/TotalSubscribers", RequestNamespace="http://tempuri.org/MembershipStats/Subscribers", ResponseNamespace="http://tempuri.org/MembershipStats/Subscribers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] TotalSubscribers() {
            object[] results = this.Invoke("TotalSubscribers", new object[0]);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void TotalSubscribersAsync() {
            this.TotalSubscribersAsync(null);
        }
        
        /// <remarks/>
        public void TotalSubscribersAsync(object userState) {
            if ((this.TotalSubscribersOperationCompleted == null)) {
                this.TotalSubscribersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTotalSubscribersOperationCompleted);
            }
            this.InvokeAsync("TotalSubscribers", new object[0], this.TotalSubscribersOperationCompleted, userState);
        }
        
        private void OnTotalSubscribersOperationCompleted(object arg) {
            if ((this.TotalSubscribersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TotalSubscribersCompleted(this, new TotalSubscribersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MembershipStats/Subscribers/SaveNewsletterEmail", RequestNamespace="http://tempuri.org/MembershipStats/Subscribers", ResponseNamespace="http://tempuri.org/MembershipStats/Subscribers", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveNewsletterEmail(string email, string pageName) {
            object[] results = this.Invoke("SaveNewsletterEmail", new object[] {
                        email,
                        pageName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaveNewsletterEmailAsync(string email, string pageName) {
            this.SaveNewsletterEmailAsync(email, pageName, null);
        }
        
        /// <remarks/>
        public void SaveNewsletterEmailAsync(string email, string pageName, object userState) {
            if ((this.SaveNewsletterEmailOperationCompleted == null)) {
                this.SaveNewsletterEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveNewsletterEmailOperationCompleted);
            }
            this.InvokeAsync("SaveNewsletterEmail", new object[] {
                        email,
                        pageName}, this.SaveNewsletterEmailOperationCompleted, userState);
        }
        
        private void OnSaveNewsletterEmailOperationCompleted(object arg) {
            if ((this.SaveNewsletterEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveNewsletterEmailCompleted(this, new SaveNewsletterEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TotalSubscribersCompletedEventHandler(object sender, TotalSubscribersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TotalSubscribersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TotalSubscribersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveNewsletterEmailCompletedEventHandler(object sender, SaveNewsletterEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveNewsletterEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveNewsletterEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591